### ISSUE TITLE
How to enhance searching?

### ISSUE THREAD

**Issue by aedart** [dauxio/daux.io#20]
Hi there

Is it possible to enhance the searching functionality, e.g. via tags, descriptions and other meta-data?
If so, how does one do so?

Currently, I could only find information about how to add / set "title" for a given page, in your official documentation.

**Comment by onigoetz** [comment]
Hello,

Yes I would love to add more information to search metadata. currently the library that I used is not very advanced and doesn't allow those things easily.

To change the title of a page, you can use Front Matter :
https://dauxio.github.io/Features/Front_Matter.html

You can add `tags` and `description` keys here as well and I will check so that they are used in the future.

**Comment by aedart** [comment]
Hi again

Thanks for your reply. I'll start adding some `tags`, `description` and ... await for a future release :)

**Comment by gerundt** [comment]
Can I look at this? :)

I would only use the word `keywords` for the *tags*. And I would also add `author`.

**Comment by onigoetz** [comment]
@gerundt Sure, if you want to :)

I don't have any preference for `keywords` or `tags` ... 

What would you use `author` for ? and documentations rarely have a single author, how would they be handled ?

**Comment by gerundt** [comment]
@onigoetz My patch use the global author as meta tag until you overwrite it in the *Front Matter*.

We use your project at work for a *IT Handbook*. Maybe we will use the `author` tag to document which IT admin write the individual page. ;-)
