### ISSUE TITLE
why not support browser cache？

### ISSUE THREAD

**Issue by catroll** [dauxio/daux.io#45]
I suggest adding some header like `Expires`, `Last-Modified`, `ETag` for daux

**Comment by onigoetz** [comment]
Hello,
Thanks for the suggestion.

I will probably add this feature, but it's not a priority.
I recommend using Daux mainly to generate the documentation as HTML and serving it statically.

Big documentations are very slow with the served version because it has to scan all directories on each request.

**Comment by onigoetz** [comment]
I will not add this feature for the moment, as explained `daux serve` or serving daux directly is meant for development. Adding caching headers is not really the purppose.

Once the files are generated, the server (nginx, apache ...) should serve the appropriate headers.
