### ISSUE TITLE
How to use subfolder

### ISSUE THREAD

**Issue by arnikasky** [dauxio/daux.io#78]
Hello Guys. 
Try to found way, how to create project in subfolder, for example https.daux.io/general/*
Can you please explain, where I should set url https.daux.io/general
Because it doesn't work.

**Comment by timitalia** [comment]
Hi @arnikasky, I've reached the same point. Did you find any solution to configure the path globaly (in the config,sjon?)?

Thanks in advance for an answer, 
Cheers Tim

**Comment by onigoetz** [comment]
Hello,
wow, sorry I missed this issue.

You don't have to set it anywhere, Daux works only with relative paths. put the folder wherever you want on your server and links will work.

**Comment by timitalia** [comment]
Hi Stéphane, 
thx for your reply! Well in my nginx configuration daux runs under a subdirectory and can only be accessed with www.domain.eu/wiki. If I build the static files and put them on the server in that subfolder, the the assets (css, js ,images...) do not get resolved because they are expected under www.domain.eu/somestyle.css. 

The only (dirty) workarround that works for me is modifying rebaseConfiguration function in the DauxHelper.php that way that I add 

$base_url = '/wiki/'; in the line above // Change base url for all links on the pages

Can this can be passed anywhere as a config param? It would be great if there would be something like 
daux generate --base-url='/wiki/' as an option

Thanks in advance for an answer,
Best regards, Tim

**Comment by onigoetz** [comment]
Did you create a custom theme ? Because the default theme generates all links in relative, so this shouldn't be needed.

**Comment by N6REJ** [comment]
@onigoetz relative pathing is relative ONLY to server root.  For example.
Looking here you see the image is properly placed and working well in storm.  i.e. links are relative.
![image](https://user-images.githubusercontent.com/1850089/66710531-2c64bc80-ed40-11e9-933a-e43306f5ddd6.png)
but once its being served, it fails.
![image](https://user-images.githubusercontent.com/1850089/66710535-3ab2d880-ed40-11e9-8204-3eb5b81c557a.png)

**Comment by onigoetz** [comment]
@N6REJ can you give me the path that it outputs for you ?

My goal is that Daux works 100% with relative paths, so that no matter what sub-folder you deploy on, it works fine. This should be the case for everything already.

**Comment by N6REJ** [comment]
public is NOT under .daux nor doc.  It's in root because thats where github/gitlab requires it to be.  Being there it automatically creates a website.
ergo daux generate ../public

**Comment by onigoetz** [comment]
Public does not have to be under daux or doc.

The relative paths are generated relative to the root of the folder in which it's generated. Where that folder is located is irrelevant.

I have made some tests as to how relative images work. Here is what I found:

| File                  | Image                             | serve | generate | Direct Markdown Render |
| --------------------- | --------------------------------- | :---: | :------: | :--------------------: |
| index.md              | react.png                         |   √   |    √     |           √            |
| index.md              | images/react.png                  |   √   |    √     |           √            |
| index.md              | 99_Extensions/images/react.png    |   √   |    X     |           √            |
| index.md              | Extensions/images/react.png       |   √   |    √     |           X            |
| 99_subfolder/index.md | react.png                         |   √   |    √     |           √            |
| 99_subfolder/index.md | ../images/react.png               |   √   |    √     |           √            |
| 99_subfolder/index.md | ../99_Extensions/images/react.png |   √   |    X     |           √            |
| 99_subfolder/index.md | ../Extensions/images/react.png    |   √   |    √     |           X            |

As you can see, relative paths work most of time expcept when a folder has a numeric prefix.
What happens is that the prefix is stripped on generation. Which means that if you have the number prefix it works in Markdown preview but not in generated form and vice versa.

I'll have a look so that the generation works if the number prefix is present so that would give a solution that works in all cases.

In the meantime, I'd recommend you use relative paths to folders without numeric prefixes.

**Comment by N6REJ** [comment]
@onigoetz a few things..
#1 public MUST be in root of the repo.  Not my requirement its' git(hub/lab)'s. and it MUST be called public
#2 don't we need to number the folders for sort order?
#3 the relative link comes from phpstorm, when I right click on it... does that make a difference?

what I'm hoping for is I can simply say "daux generate" and it will put things in the proper "public" folder automatically.
lastly, I need to be in the .daux/doc folder when I do the generate right?

**Comment by onigoetz** [comment]
1. As I said, how you name and where you put your output directory is not important to Daux, you can put it wherever you want. Daux's documentation itself is published with GitHub Pages ( ﻿https://github.com/dauxio/daux.io/blob/master/.travis.yml#L25-L37 )
2. It's not mandatory, it's an option that you have. But in the case of relative images, there is this current limitations. If you omit the numbers, it will be sorted alphabetically.
3. No, which IDE you use doesn't make a difference, the difference is on the fact that the folder with number prefixes exists before generating and doesn't exist (is renamed) after generating.

For your last question, let's take this example hierarchy

- your_repo/
  - documentation/
    - docs/
       - index.md
       - other_page.md

You need to be in `your_repo/documentation` to run `daux generate --destination=public` and it will generate in `your_repo/documentation/public` or with `daux generate --destination=../public` it will generate in `your_repo/public`

```
- 
```

**Comment by N6REJ** [comment]
right daux generate --destination=../public is what I've been using, I'm just hoping y'all will create a way to put the destination in the config file so that daux generate is enough

**Comment by onigoetz** [comment]
The fixes discussed in this issue are available in [version 0.12](https://github.com/dauxio/daux.io/releases/tag/0.12.0)
