### ISSUE TITLE
Website Footer Outdated

### ISSUE THREAD

**Issue by firstworldengineer** [dauxio/daux.io#80]
There's no contact info on the daux.io website, so not sure how to let you guys know that the github repo link on your footer point to the deprecated repo.

**Comment by onigoetz** [comment]
Hello @firstworldengineer 

Sadly, I can't do anything about it. I don't have ownership over the daux.io website, I've tried contacting the previous owner, ( https://github.com/justinwalsh/daux.io/issues/452 ) But didn't have any success in doing so. That's why the current website is : https://dauxio.github.io/

I've had no answer on my multiple attempts to make contact with him since he added me as a maintainer on the repository.

@justinwalsh My offer still stands to buy the daux.io domain from you. I'm open to discussion. I understand you're a busy person, and would very much appreciate a little bit of your time.

**Comment by justinwalsh** [comment]
The domain is now setup as a custom address for the pages repo.

**Comment by onigoetz** [comment]
That's awesome, thank you !

**Comment by firstworldengineer** [comment]
👍🏻 awesome!
